[package]
name = "payload-gen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
session-state = { workspace = true }
sha2 = { workspace = true }
md-5 = { workspace = true }
hex = { workspace = true }
core-utils = { workspace = true }
phf = { workspace = true }
thiserror = { workspace = true }
smallvec = { workspace = true }
